SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS SIFDEMO DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE SIFDEMO ;

-- -----------------------------------------------------
-- Table SIFDEMO.SCHOOL
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS SCHOOL (
  REF_ID VARCHAR(32)  NULL ,
  LOCAL_ID VARCHAR(10) NOT NULL ,
  SCHOOL_NAME VARCHAR(45) NULL ,
  DISTRICT_ID VARCHAR(10) NULL ,
  DISTRICT_NAME VARCHAR(45) NULL ,
  SCHOOL_TYPE VARCHAR(10) NULL ,
  GOVERNMENT_SCHOOL VARCHAR(1) NULL COMMENT 'Y=Yes, N=No' ,
  RELIGIOUS_AFFILIATION VARCHAR(10) NULL ,
  PRIMARY KEY (LOCAL_ID) )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table STUDENT
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS STUDENT (
  SIF_REFID VARCHAR(32) NULL ,
  LOCAL_ID VARCHAR(20) NOT NULL ,
  YOUNG_CARER VARCHAR(1) NULL ,
  HAS_DISABLITY VARCHAR(1) NULL ,
  FIRST_NAME VARCHAR(30) NOT NULL ,
  MIDDLE_NAME VARCHAR(30) NULL ,
  LAST_NAME VARCHAR(30) NOT NULL ,
  TITLE VARCHAR(10) NULL ,
  GENDER VARCHAR(1) NULL ,
  LANGAUGE_AT_HOME VARCHAR(5) NULL ,
  DOB DATE NULL ,
  STREET_NAME_AND_NO VARCHAR(45) NULL ,
  CITY VARCHAR(45) NOT NULL ,
  POST_CODE VARCHAR(4) NULL ,
  STATE VARCHAR(3) NULL ,
  PHONE_NUMBER VARCHAR(20) NULL ,
  PHONE_TYPE VARCHAR(4) NULL ,
  PRIMARY KEY (LOCAL_ID) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
