insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '4700', 'Duncraig Primary', '01', 'Joondalup', 'PRIMARY', 'Y', null);
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '4800', 'Carine Snr High', '02', 'Stirling', 'HIGH', 'Y', null);
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '4900', 'St. Stevens Primary', '01', 'Joondalup', 'PRIMARY', 'N', 'CATHOLIC');
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '5000', 'Scarborough High', '02', 'Stirling', 'HIGH', 'Y', null);
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '5100', 'Kununurra Remote High', '20', 'Kimberley', 'HIGH', 'Y', null);
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '5200', 'Ballajura High', '15', 'Wanneroo', 'High', null, 'Rastafari');
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '5300', 'Warburton Remote School', '18', 'Interior WA', null, null, null);

